<?php
/**
 * Created by PhpStorm.
 * User: root
 * Date: 31.03.16
 * Time: 12:09
 */

namespace AppTest\Action;


use App\Action\HelloActionFactory;
use Interop\Container\ContainerInterface;
use Zend\Diactoros\Response;
use Zend\Diactoros\ServerRequest;
use Zend\Expressive\Template\TemplateRendererInterface;

class HelloActionFactoryTest extends \PHPUnit_Framework_TestCase
{
    /** @var  ContainerInterface */
    private $container;
    public function setUp()
    {

        $this->container = $this->prophesize(ContainerInterface::class);
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testFactoryWithTemplate(){

        $factory = new HelloActionFactory();
        $this->container->get(TemplateRendererInterface::class)->willRetur($this->prophesize(TemplateRendererInterface::class));
        $helloPage = $factory($this->container->reveal());
        $this->assertTrue($helloPage instanceof Response);
    }
}
